site_name: Cubinterpp Documentation
site_url: https://swvanbuuren.github.io/cubinterpp/
repo_url: https://github.com/swvanbuuren/cubinterpp
repo_name: swvanbuuren/cubinterpp

theme:
  name: material
  features:
  - navigation.sections
  - navigation.tabs
  - navigation.indexes
  - content.code.annotate
  - content.code.copy

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_toc_entry: false
  - mkdoxy:
      projects:
        reference:
          src-dirs: include/ src/
          full-doc: True
          doxy-cfg:
            FILE_PATTERNS: "*.cpp *.h*"
            EXAMPLE_PATH: examples
            RECURSIVE: True

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      url_download: true
  - pymdownx.superfences
  - footnotes
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Cubinterpp:
    - index.md
    - Introduction: introduction.md
    - Requirements: requirements.md
    - Usage instructions: usage.md
  - Mathematical Background:
    - theory/index.md
    - Linear interpolation: theory/linear.md
    - Cubic interpolation: theory/cubic.md
  - Code Reference:
    - reference/index.md
    - Links: reference/links.md
    - Classes:
        - Class List: reference/annotated.md
        - Class Index: reference/classes.md
        - Class Hierarchy: reference/hierarchy.md
        - Class Members: reference/class_members.md
        - Class Member Functions: reference/class_member_functions.md
        - Class Member Variables: reference/class_member_variables.md
        - Class Member Typedefs: reference/class_member_typedefs.md
        - Class Member Enumerations: reference/class_member_enums.md
    - Namespaces:
        - Namespace List: reference/namespaces.md
        - Namespace Members: reference/namespace_members.md
        - Namespace Member Functions: reference/namespace_member_functions.md
        - Namespace Member Variables: reference/namespace_member_variables.md
        - Namespace Member Typedefs: reference/namespace_member_typedefs.md
        - Namespace Member Enumerations: reference/namespace_member_enums.md
    - Functions: reference/functions.md
    - Variables: reference/variables.md
    - Macros: reference/macros.md
    - Files: reference/files.md
